<?php

use Illuminate\Database\Seeder;
use App\Model\ProfessionType;
class ProfessionTypeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ProfessionType::insert([
            ['professionTypeName'=>'Army Officer'],
            ['professionTypeName'=>'Accountant'],
            ['professionTypeName'=>'Actor / Actress'],
            ['professionTypeName'=>'Architect'],
            ['professionTypeName'=>'Artist'],
            ['professionTypeName'=>'Author'],
            ['professionTypeName'=>'Blogger'],
            ['professionTypeName'=>'Beauty Therapist'],
            ['professionTypeName'=>'Body Artist Or Mehedi-Alpona'],
            ['professionTypeName'=>'Banker'],
            ['professionTypeName'=>'Builder'],
            ['professionTypeName'=>'Business'],
            ['professionTypeName'=>'Computer Operator'],
            ['professionTypeName'=>'Carpenter'],
            ['professionTypeName'=>'Civil Engineer'],
            ['professionTypeName'=>'Cook'],
            ['professionTypeName'=>'Dentist'],
            ['professionTypeName'=>'Dancer Or Choreographer'],
            ['professionTypeName'=>'Designer'],
            ['professionTypeName'=>'Developer'],
            ['professionTypeName'=>'Doctor'],
            ['professionTypeName'=>'Diver'],
            ['professionTypeName'=>'Economist'],
            ['professionTypeName'=>'Editor'],
            ['professionTypeName'=>'Electrician'],
            ['professionTypeName'=>'Engineer'],
            ['professionTypeName'=>'Fashion Designer'],
            ['professionTypeName'=>'Farmer'],
            ['professionTypeName'=>'Filmmaker'],
            ['professionTypeName'=>'Fisherman'],
            ['professionTypeName'=>'Graphic Designer'],
            ['professionTypeName'=>'Hotel Manager'],
            ['professionTypeName'=>'Horse Wife'],
            ['professionTypeName'=>'Interior Designer'],
            ['professionTypeName'=>'Jeweler'],
            ['professionTypeName'=>'Journalist'],
            ['professionTypeName'=>'Lawyer'],
            ['professionTypeName'=>'Mechanic'],
            ['professionTypeName'=>'Musician'],
            ['professionTypeName'=>'Member Of Parliament'],
            ['professionTypeName'=>'Nurse'],
            ['professionTypeName'=>'Network Engineer'],
            ['professionTypeName'=>'Poet'],
            ['professionTypeName'=>'Painter'],
            ['professionTypeName'=>'Pharmacist'],
            ['professionTypeName'=>'Photographer'],
            ['professionTypeName'=>'Physician'],
            ['professionTypeName'=>'Police Officer'],
            ['professionTypeName'=>'Politician'],
            ['professionTypeName'=>'Professor'],
            ['professionTypeName'=>'Planner'],
            ['professionTypeName'=>'Programmer'],
            ['professionTypeName'=>'Receptionist'],
            ['professionTypeName'=>'Singer'],
            ['professionTypeName'=>'Sales And Marketing Manager'],
            ['professionTypeName'=>'Sales Representative'],
            ['professionTypeName'=>'Software Engineer'],
            ['professionTypeName'=>'Social Worker'],
            ['professionTypeName'=>'Security Officer'],
            ['professionTypeName'=>'Public Relations Officer'],
            ['professionTypeName'=>'Publisher'],
            ['professionTypeName'=>'Teacher'],
            ['professionTypeName'=>'Tour Guide'],
            ['professionTypeName'=>'Travel Consultant'],
            ['professionTypeName'=>'Tattoo Artist'],
            ['professionTypeName'=>'Translator'],
            ['professionTypeName'=>'Veterinarian'],
            ['professionTypeName'=>'Video Editor'],
            ['professionTypeName'=>'Web Developer'],
            ['professionTypeName'=>'Writer'],
            ['professionTypeName'=>'Freelancer'],
            ['professionTypeName'=>'Employer'],
            ['professionTypeName'=>'Gov. Job'],
            ['professionTypeName'=>'Officer'],
            ['professionTypeName'=>'Student'],
            ['professionTypeName'=>'Club Member'],
            ['professionTypeName'=>'Organizer'],
            ['professionTypeName'=>'Entrepreneur'],
            ['professionTypeName'=>'Professor/Lecture'],
            ['professionTypeName'=>'Industrialist'],
            ['professionTypeName'=>'Contractor'],
            ['professionTypeName'=>'Supplier'],
            ['professionTypeName'=>'Worker'],
            ['professionTypeName'=>'Mctchmaker'],
            ['professionTypeName'=>'Shelf Employer'],
            ['professionTypeName'=>'Chirmam'],
            ['professionTypeName'=>'Up Member'],
            ['professionTypeName'=>'Club Member'],
            ['professionTypeName'=>'Director'],
            ['professionTypeName'=>'Dg/Md'],
            ['professionTypeName'=>'Waiting For Job'],
            ['professionTypeName'=>'Booster/Helper'],
            ['professionTypeName'=>'Expat'],
            ['professionTypeName'=>'Broker'],
            ['professionTypeName'=>'Sprotsman'],
            ['professionTypeName'=>'Shopkeeper'],
            ['professionTypeName'=>'Media Worker'],
            ['professionTypeName'=>'Retired'],
            ['professionTypeName'=>'Stroller'],
            ['professionTypeName'=>'Secretary'],
            ['professionTypeName'=>'Adviser/Ps/Po'],
           
        ]);
    }
}
