<?php

use Illuminate\Database\Seeder;
use App\Model\Thana;

class ThanaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Thana::create(['id'=>'7','name'=>'Faridpur Sadar','district_id'=>'49']);
// Thana::create(['id'=>'8','name'=>'Saltha','district_id'=>'49']);
// Thana::create(['id'=>'9','name'=>'Nagarkanda','district_id'=>'49']);
// Thana::create(['id'=>'10','name'=>'Alfadanga','district_id'=>'49']);
// Thana::create(['id'=>'11','name'=>'Bowalmari','district_id'=>'49']);
// Thana::create(['id'=>'12','name'=>'Modhukhali','district_id'=>'49']);
// Thana::create(['id'=>'13','name'=>'Vanga','district_id'=>'49']);
// Thana::create(['id'=>'14','name'=>'Sadarpur','district_id'=>'49']);
// Thana::create(['id'=>'16','name'=>'Rajbari Sadar','district_id'=>'50']);
// Thana::create(['id'=>'17','name'=>'Guwalando','district_id'=>'50']);
// Thana::create(['id'=>'18','name'=>'Pangsha','district_id'=>'50']);
// Thana::create(['id'=>'19','name'=>'Baliyakandi','district_id'=>'50']);
// Thana::create(['id'=>'20','name'=>'Gopalgonj Sadar','district_id'=>'105']);
// Thana::create(['id'=>'21','name'=>'Kotalipara','district_id'=>'105']);
// Thana::create(['id'=>'22','name'=>'Tongi para','district_id'=>'105']);
// Thana::create(['id'=>'23','name'=>'Muksod pur','district_id'=>'105']);
// Thana::create(['id'=>'24','name'=>'Kashiyani','district_id'=>'105']);
// Thana::create(['id'=>'25','name'=>'Magura Sadar','district_id'=>'99']);
// Thana::create(['id'=>'26','name'=>'Sripur','district_id'=>'99']);
// Thana::create(['id'=>'27','name'=>'Shalikha','district_id'=>'99']);
// Thana::create(['id'=>'28','name'=>'Mohammadpur','district_id'=>'99']);
// Thana::create(['id'=>'29','name'=>'Boalkhali','district_id'=>'116']);
// Thana::create(['id'=>'34','name'=>'Chandanaish','district_id'=>'116']);
// Thana::create(['id'=>'35','name'=>'Fatikchhari','district_id'=>'116']);
// Thana::create(['id'=>'36','name'=>'Hathazari','district_id'=>'116']);
// Thana::create(['id'=>'37','name'=>'Lohagara','district_id'=>'116']);
// Thana::create(['id'=>'38','name'=>'Mirsharai','district_id'=>'116']);
// Thana::create(['id'=>'39','name'=>'Patiya','district_id'=>'116']);
// Thana::create(['id'=>'40','name'=>'Rangunia','district_id'=>'116']);
// Thana::create(['id'=>'41','name'=>'Raozan','district_id'=>'116']);
// Thana::create(['id'=>'42','name'=>'Sandwip','district_id'=>'116']);
// Thana::create(['id'=>'43','name'=>'Satkania','district_id'=>'116']);
// Thana::create(['id'=>'44','name'=>'Sitakunda','district_id'=>'116']);
// Thana::create(['id'=>'45','name'=>'Barura','district_id'=>'70']);
// Thana::create(['id'=>'46','name'=>'Brahmanpara','district_id'=>'70']);
// Thana::create(['id'=>'47','name'=>'Burichong','district_id'=>'70']);
// Thana::create(['id'=>'48','name'=>'Chandina','district_id'=>'70']);
// Thana::create(['id'=>'49','name'=>'Chauddagram','district_id'=>'70']);
// Thana::create(['id'=>'50','name'=>'Daudkandi','district_id'=>'70']);
// Thana::create(['id'=>'51','name'=>'Debidwar','district_id'=>'70']);
// Thana::create(['id'=>'52','name'=>'Homna','district_id'=>'70']);
// Thana::create(['id'=>'53','name'=>'Comilla Adarsa Sadar','district_id'=>'70']);
// Thana::create(['id'=>'54','name'=>'Laksam','district_id'=>'70']);
// Thana::create(['id'=>'55','name'=>'Monohorgonj','district_id'=>'70']);
// Thana::create(['id'=>'56','name'=>'Meghna','district_id'=>'70']);
// Thana::create(['id'=>'57','name'=>'Muradnagar','district_id'=>'70']);
// Thana::create(['id'=>'58','name'=>'Nangalkot','district_id'=>'70']);
// Thana::create(['id'=>'59','name'=>'Comilla Sadar South','district_id'=>'70']);
// Thana::create(['id'=>'60','name'=>'Titas','district_id'=>'70']);
// Thana::create(['id'=>'61','name'=>'Feni sadar','district_id'=>'74']);
// Thana::create(['id'=>'62','name'=>'Chagalnaiya','district_id'=>'74']);
// Thana::create(['id'=>'63','name'=>'Daganbhyan','district_id'=>'74']);
// Thana::create(['id'=>'64','name'=>'Parshuram','district_id'=>'74']);
// Thana::create(['id'=>'65','name'=>'Fhulgazi','district_id'=>'74']);
// Thana::create(['id'=>'66','name'=>'Sonagazi','district_id'=>'74']);
// Thana::create(['id'=>'67','name'=>'Dighinala','district_id'=>'76']);
// Thana::create(['id'=>'68','name'=>'Khagrachhari','district_id'=>'76']);
// Thana::create(['id'=>'69','name'=>'Lakshmichhari','district_id'=>'76']);
// Thana::create(['id'=>'70','name'=>'Mahalchhari','district_id'=>'76']);
// Thana::create(['id'=>'71','name'=>'Manikchhari','district_id'=>'76']);
// Thana::create(['id'=>'72','name'=>'Matiranga','district_id'=>'76']);
// Thana::create(['id'=>'73','name'=>'Panchhar','district_id'=>'76']);
// Thana::create(['id'=>'74','name'=>'Ramgarh','district_id'=>'76']);
// Thana::create(['id'=>'75','name'=>'Laxmipur Sadar','district_id'=>'73']);
// Thana::create(['id'=>'76','name'=>'Raipur','district_id'=>'73']);
// Thana::create(['id'=>'77','name'=>'Ramganj','district_id'=>'73']);
// Thana::create(['id'=>'78','name'=>'Ramgati','district_id'=>'73']);
// Thana::create(['id'=>'79','name'=>'Komol Nagar','district_id'=>'73']);
// Thana::create(['id'=>'80','name'=>'Begumganj','district_id'=>'72']);
// Thana::create(['id'=>'81','name'=>'Chatkhil','district_id'=>'72']);
// Thana::create(['id'=>'82','name'=>'Companiganj','district_id'=>'72']);
// Thana::create(['id'=>'83','name'=>'Hatiya','district_id'=>'72']);
// Thana::create(['id'=>'84','name'=>'Noakhali Sadar','district_id'=>'72']);
// Thana::create(['id'=>'85','name'=>'Senbagh','district_id'=>'72']);
// Thana::create(['id'=>'86','name'=>'Sonaimuri','district_id'=>'72']);
// Thana::create(['id'=>'87','name'=>'Rangamati Sadar','district_id'=>'77']);
// Thana::create(['id'=>'88','name'=>'Belaichhari','district_id'=>'77']);
// Thana::create(['id'=>'89','name'=>'Bagaichhari','district_id'=>'77']);
// Thana::create(['id'=>'90','name'=>'Barkal','district_id'=>'77']);
// Thana::create(['id'=>'91','name'=>'Juraichhari','district_id'=>'77']);
// Thana::create(['id'=>'92','name'=>'Rajasthali','district_id'=>'77']);
// Thana::create(['id'=>'93','name'=>'Kaptai','district_id'=>'77']);
// Thana::create(['id'=>'94','name'=>'Langadu','district_id'=>'77']);
// Thana::create(['id'=>'95','name'=>'Nannerchar','district_id'=>'77']);
// Thana::create(['id'=>'96','name'=>'Kaukhali','district_id'=>'77']);
// Thana::create(['id'=>'97','name'=>'Dohar','district_id'=>'56']);
// Thana::create(['id'=>'98','name'=>'Dhamrai','district_id'=>'56']);
// Thana::create(['id'=>'99','name'=>'Nawabgonj','district_id'=>'56']);
// Thana::create(['id'=>'100','name'=>'Gazipur Sadar','district_id'=>'58']);
// Thana::create(['id'=>'101','name'=>'Joydebpur','district_id'=>'58']);
// Thana::create(['id'=>'102','name'=>'Kaliakior','district_id'=>'58']);
// Thana::create(['id'=>'103','name'=>'Kapasia','district_id'=>'58']);
// Thana::create(['id'=>'104','name'=>'Sripur','district_id'=>'58']);
// Thana::create(['id'=>'105','name'=>'Kaliganj','district_id'=>'58']);
// Thana::create(['id'=>'106','name'=>'Tongi','district_id'=>'58']);
// Thana::create(['id'=>'107','name'=>'Dewanganj','district_id'=>'62']);
// Thana::create(['id'=>'108','name'=>'Baksiganj','district_id'=>'62']);
// Thana::create(['id'=>'109','name'=>'Islampur','district_id'=>'62']);
// Thana::create(['id'=>'110','name'=>'Jamalpur Sadar','district_id'=>'62']);
// Thana::create(['id'=>'111','name'=>'Madarganj','district_id'=>'62']);
// Thana::create(['id'=>'112','name'=>'Melandaha','district_id'=>'62']);
// Thana::create(['id'=>'113','name'=>'Sarishabari','district_id'=>'62']);
// Thana::create(['id'=>'114','name'=>'Astagram','district_id'=>'59']);
// Thana::create(['id'=>'115','name'=>'Bajitpur','district_id'=>'59']);
// Thana::create(['id'=>'116','name'=>'Bhairab','district_id'=>'59']);
// Thana::create(['id'=>'117','name'=>'Hossainpur','district_id'=>'59']);
// Thana::create(['id'=>'118','name'=>'Itna','district_id'=>'59']);
// Thana::create(['id'=>'119','name'=>'Karimganj','district_id'=>'59']);
// Thana::create(['id'=>'120','name'=>'Katiadi','district_id'=>'59']);
// Thana::create(['id'=>'121','name'=>'Kishoreganj Sadar','district_id'=>'59']);
// Thana::create(['id'=>'122','name'=>'Kuliarchar','district_id'=>'59']);
// Thana::create(['id'=>'123','name'=>'Mithamain','district_id'=>'59']);
// Thana::create(['id'=>'124','name'=>'Nikli','district_id'=>'59']);
// Thana::create(['id'=>'125','name'=>'Pakundia','district_id'=>'59']);
// Thana::create(['id'=>'126','name'=>'Tarail','district_id'=>'59']);
// Thana::create(['id'=>'127','name'=>'Madaripur Sadar','district_id'=>'52']);
// Thana::create(['id'=>'128','name'=>'Kalkini','district_id'=>'52']);
// Thana::create(['id'=>'129','name'=>'Rajoir','district_id'=>'52']);
// Thana::create(['id'=>'130','name'=>'shibchar','district_id'=>'52']);
// Thana::create(['id'=>'131','name'=>'Manikganj Sadar','district_id'=>'54']);
// Thana::create(['id'=>'132','name'=>'Singair','district_id'=>'54']);
// Thana::create(['id'=>'133','name'=>'Shivalaya','district_id'=>'54']);
// Thana::create(['id'=>'134','name'=>'Saturia','district_id'=>'54']);
// Thana::create(['id'=>'135','name'=>'Harirampur','district_id'=>'54']);
// Thana::create(['id'=>'136','name'=>'Ghior','district_id'=>'54']);
// Thana::create(['id'=>'137','name'=>'Daulatpur','district_id'=>'54']);
// Thana::create(['id'=>'138','name'=>'Lohajang','district_id'=>'55']);
// Thana::create(['id'=>'139','name'=>'Sreenagar','district_id'=>'55']);
// Thana::create(['id'=>'140','name'=>'Munshiganj Sadar','district_id'=>'55']);
// Thana::create(['id'=>'141','name'=>'Sirajdikhan','district_id'=>'55']);
// Thana::create(['id'=>'142','name'=>'Tongibari','district_id'=>'55']);
// Thana::create(['id'=>'143','name'=>'Gazaria','district_id'=>'55']);
// Thana::create(['id'=>'144','name'=>'Bhaluka','district_id'=>'60']);
// Thana::create(['id'=>'145','name'=>'Trishal','district_id'=>'60']);
// Thana::create(['id'=>'146','name'=>'Haluaghat','district_id'=>'60']);
// Thana::create(['id'=>'147','name'=>'Muktagachha','district_id'=>'60']);
// Thana::create(['id'=>'148','name'=>'Dhobaura','district_id'=>'60']);
// Thana::create(['id'=>'149','name'=>'60']);
// Thana::create(['id'=>'150','name'=>'Gaffargaon60']);
// Thana::create(['id'=>'151','name'=>'Gauripur60']);
// Thana::create(['id'=>'152','name'=>'Ishwarganj60']);
// Thana::create(['id'=>'153','name'=>'Mymensingh Sadar60']);
// Thana::create(['id'=>'154','name'=>'Nandail60']);
// Thana::create(['id'=>'155','name'=>'Phulpur60']);
// Thana::create(['id'=>'156','name'=>'Araihazar57']);
// Thana::create(['id'=>'157','name'=>'Sonargaon57']);
// Thana::create(['id'=>'158','name'=>'Bandar57']);
// Thana::create(['id'=>'159','name'=>'Naryanganj Sadar57']);
// Thana::create(['id'=>'160','name'=>'Rupganj57']);
// Thana::create(['id'=>'161','name'=>'Siddirgonj57']);
// Thana::create(['id'=>'162','name'=>'Siddirgonj57']);
// Thana::create(['id'=>'163','name'=>'Belabo112']);
// Thana::create(['id'=>'164','name'=>'Monohardi112']);
// Thana::create(['id'=>'165','name'=>'Narsingdi Sadar112']);
// Thana::create(['id'=>'166','name'=>'Palash112']);
// Thana::create(['id'=>'167','name'=>'Raipura112']);
// Thana::create(['id'=>'168','name'=>'Shibpur112']);
// Thana::create(['id'=>'169','name'=>'Durgapur64']);
// Thana::create(['id'=>'171','name'=>'Kalmakanda64']);
// Thana::create(['id'=>'172','name'=>'Purbadhala64']);
// Thana::create(['id'=>'173','name'=>'Netrokona Sadar64']);
// Thana::create(['id'=>'174','name'=>'Atpara64']);
// Thana::create(['id'=>'175','name'=>'Mohongonj64']);
// Thana::create(['id'=>'177','name'=>'Madan64']);
// Thana::create(['id'=>'178','name'=>'Khaliajuri64']);
// Thana::create(['id'=>'179','name'=>'Shariatpur53']);
// Thana::create(['id'=>'180','name'=>'Damudya53']);
// Thana::create(['id'=>'181','name'=>'Naria53']);
// Thana::create(['id'=>'182','name'=>'Jajira53']);
// Thana::create(['id'=>'183','name'=>'Bhedarganj53']);
// Thana::create(['id'=>'184','name'=>'Gosairhat53']);
// Thana::create(['id'=>'185','name'=>'Shakhipur53']);
// Thana::create(['id'=>'186','name'=>'Jhenaigati63']);
// Thana::create(['id'=>'187','name'=>'Nakla63']);
// Thana::create(['id'=>'188','name'=>'Nalitabari63']);
// Thana::create(['id'=>'189','name'=>'Sherpur Sadar63']);
// Thana::create(['id'=>'190','name'=>'Sreebardi63']);
// Thana::create(['id'=>'191','name'=>'Tangail Sadar61']);
// Thana::create(['id'=>'192','name'=>'Sakhipur61']);
// Thana::create(['id'=>'193','name'=>'Basail61']);
// Thana::create(['id'=>'194','name'=>'Madhupur61']);
// Thana::create(['id'=>'195','name'=>'Ghatail61']);
// Thana::create(['id'=>'196','name'=>'Kalihati61']);
// Thana::create(['id'=>'197','name'=>'Nagarpur61']);
// Thana::create(['id'=>'198','name'=>'Mirzapur61']);
// Thana::create(['id'=>'199','name'=>'Gopalpur61']);
// Thana::create(['id'=>'200','name'=>'Delduar61']);
// Thana::create(['id'=>'201','name'=>'Bhuapur61']);
// Thana::create(['id'=>'202','name'=>'Dhonbari61']);
// Thana::create(['id'=>'203','name'=>'Bagerhat Sadar104']);
// Thana::create(['id'=>'204','name'=>'Chitalmari104']);
// Thana::create(['id'=>'205','name'=>'Fakirhat104']);
// Thana::create(['id'=>'206','name'=>'Kachua104']);
// Thana::create(['id'=>'207','name'=>'Mollahat104']);
// Thana::create(['id'=>'208','name'=>'Mongla104']);
// Thana::create(['id'=>'209','name'=>'Morrelganj104']);
// Thana::create(['id'=>'210','name'=>'Rampal104']);
// Thana::create(['id'=>'211','name'=>'Sarankhola104']);
// Thana::create(['id'=>'212','name'=>'Char vodrashon49']);
// Thana::create(['id'=>'215','name'=>'Iswardi93']);
// Thana::create(['id'=>'217','name'=>'Terokhada103']);
// Thana::create(['id'=>'218','name'=>'Batiaghata103']);
// Thana::create(['id'=>'219','name'=>'Dacope103']);
// Thana::create(['id'=>'220','name'=>'Dumuria103']);
// Thana::create(['id'=>'221','name'=>'Dighalia103']);
// Thana::create(['id'=>'222','name'=>'Koyra103']);
// Thana::create(['id'=>'223','name'=>'Paikgachha103']);
// Thana::create(['id'=>'224','name'=>'Phultala103']);
// Thana::create(['id'=>'225','name'=>'Rupsa103']);
// Thana::create(['id'=>'226','name'=>'Kushtia Sadar95']);
// Thana::create(['id'=>'227','name'=>'Kumarkhali95']);
// Thana::create(['id'=>'228','name'=>'Daulatpur95']);
// Thana::create(['id'=>'229','name'=>'Mirpur95']);
// Thana::create(['id'=>'230','name'=>'Bheramara95']);
// Thana::create(['id'=>'231','name'=>'Khoksa95']);
// Thana::create(['id'=>'232','name'=>'Magura Sadar99']);
// Thana::create(['id'=>'233','name'=>'Mohammadpur99']);
// Thana::create(['id'=>'234','name'=>'Shalikha99']);
// Thana::create(['id'=>'235','name'=>'Sreepur99']);
// Thana::create(['id'=>'236','name'=>'Meher pur Sadar96']);
// Thana::create(['id'=>'237','name'=>'Gangni96']);
// Thana::create(['id'=>'238','name'=>'Mujib nagar96']);
// Thana::create(['id'=>'239','name'=>'Narail Sadar100']);
// Thana::create(['id'=>'240','name'=>'Kalia100']);
// Thana::create(['id'=>'241','name'=>'Lohagara100']);
// Thana::create(['id'=>'242','name'=>'Satkhira Sadar102']);
// Thana::create(['id'=>'243','name'=>'Assasuni102']);
// Thana::create(['id'=>'244','name'=>'Debhata102']);
// Thana::create(['id'=>'245','name'=>'Tala102']);
// Thana::create(['id'=>'246','name'=>'Kalaroa102']);
// Thana::create(['id'=>'247','name'=>'Kaliganj102']);
// Thana::create(['id'=>'248','name'=>'Shyamnagar102']);
// Thana::create(['id'=>'249','name'=>'Adamdighi87']);
// Thana::create(['id'=>'250','name'=>'Bogra Sadar87']);
// Thana::create(['id'=>'251','name'=>'Dhunat87']);
// Thana::create(['id'=>'252','name'=>'Dupchanchia87']);
// Thana::create(['id'=>'253','name'=>'Gabtali87']);
// Thana::create(['id'=>'254','name'=>'Kahaloo87']);
// Thana::create(['id'=>'255','name'=>'Nandigram87']);
// Thana::create(['id'=>'256','name'=>'Sahajanpur87']);
// Thana::create(['id'=>'257','name'=>'Sariakandi87']);
// Thana::create(['id'=>'258','name'=>'Sherpur87']);
// Thana::create(['id'=>'259','name'=>'Shibganj87']);
// Thana::create(['id'=>'260','name'=>'Sonatala87']);
// Thana::create(['id'=>'261','name'=>'Akkelpur88']);
// Thana::create(['id'=>'262','name'=>'Joypurhat Sadar88']);
// Thana::create(['id'=>'263','name'=>'Kalai88']);
// Thana::create(['id'=>'264','name'=>'Khetlal88']);
// Thana::create(['id'=>'265','name'=>'Panchbibi88']);
// Thana::create(['id'=>'266','name'=>'Naogaon89']);
// Thana::create(['id'=>'267','name'=>'Manda89']);
// Thana::create(['id'=>'268','name'=>'Niamatpur89']);
// Thana::create(['id'=>'269','name'=>'Atrai89']);
// Thana::create(['id'=>'270','name'=>'Raninagar89']);
// Thana::create(['id'=>'271','name'=>'Patnitala89']);
// Thana::create(['id'=>'272','name'=>'Mahadevpur89']);
// Thana::create(['id'=>'273','name'=>'Dhamoirhat89']);
// Thana::create(['id'=>'274','name'=>'Sapahar89']);
// Thana::create(['id'=>'275','name'=>'Porsha89']);
// Thana::create(['id'=>'276','name'=>'Badalgachhi89']);
// Thana::create(['id'=>'277','name'=>'Singra92']);
// Thana::create(['id'=>'278','name'=>'Boraigram92']);
// Thana::create(['id'=>'279','name'=>'Gurudaspur92']);
// Thana::create(['id'=>'280','name'=>'Bagatipara92']);
// Thana::create(['id'=>'281','name'=>'Lalpur92']);
// Thana::create(['id'=>'282','name'=>'Natore Sadar92']);
// Thana::create(['id'=>'283','name'=>'Baraigram92']);
// Thana::create(['id'=>'284','name'=>'Bholahat90']);
// Thana::create(['id'=>'285','name'=>'Gomastapur90']);
// Thana::create(['id'=>'286','name'=>'Nachole90']);
// Thana::create(['id'=>'287','name'=>'Nawabganj Sadar90']);
// Thana::create(['id'=>'288','name'=>'Shibganj90']);
// Thana::create(['id'=>'289','name'=>'Atgharia93']);
// Thana::create(['id'=>'290','name'=>'Bera93']);
// Thana::create(['id'=>'291','name'=>'Bhangura93']);
// Thana::create(['id'=>'292','name'=>'Chatmohar93']);
// Thana::create(['id'=>'293','name'=>'Faridpur93']);
// Thana::create(['id'=>'294','name'=>'Ishwardi93']);
// Thana::create(['id'=>'295','name'=>'Pabna Sadar93']);
// Thana::create(['id'=>'296','name'=>'Santhia93']);
// Thana::create(['id'=>'297','name'=>'Sujanagar93']);
// Thana::create(['id'=>'298','name'=>'Bagha91']);
// Thana::create(['id'=>'299','name'=>'Bagmara91']);
// Thana::create(['id'=>'300','name'=>'Charghat91']);
// Thana::create(['id'=>'301','name'=>'Durgapur91']);
// Thana::create(['id'=>'302','name'=>'Godagari91']);
// Thana::create(['id'=>'303','name'=>'Mohanpur91']);
// Thana::create(['id'=>'304','name'=>'Paba91']);
// Thana::create(['id'=>'305','name'=>'Puthia91']);
// Thana::create(['id'=>'306','name'=>'Tanore91']);
// Thana::create(['id'=>'307','name'=>'Ramna56']);
// Thana::create(['id'=>'309','name'=>'Dhanmondi56']);
// Thana::create(['id'=>'310','name'=>'Hajaribag56']);
// Thana::create(['id'=>'311','name'=>'New market56']);
// Thana::create(['id'=>'312','name'=>'Shahabag56']);
// Thana::create(['id'=>'313','name'=>'Kala Bagan56']);
// Thana::create(['id'=>'314','name'=>'Lal bag56']);
// Thana::create(['id'=>'315','name'=>'Kotowali56']);
// Thana::create(['id'=>'316','name'=>'Kamrangirchar56']);
// Thana::create(['id'=>'317','name'=>'Chalk bazar56']);
// Thana::create(['id'=>'318','name'=>'Bangshal56']);
// Thana::create(['id'=>'319','name'=>'Sutrapur56']);
// Thana::create(['id'=>'320','name'=>'Shampur56']);
// Thana::create(['id'=>'321','name'=>'Jatrabari56']);
// Thana::create(['id'=>'322','name'=>'Demra56']);
// Thana::create(['id'=>'323','name'=>'Kadamtoli56']);
// Thana::create(['id'=>'324','name'=>'Gendaria56']);
// Thana::create(['id'=>'325','name'=>'Motijheel56']);
// Thana::create(['id'=>'326','name'=>'Polton56']);
// Thana::create(['id'=>'327','name'=>'subojbag56']);
// Thana::create(['id'=>'329','name'=>'Khilgoun56']);
// Thana::create(['id'=>'330','name'=>'Rampura56']);
// Thana::create(['id'=>'331','name'=>'Tejgoun56']);
// Thana::create(['id'=>'332','name'=>'Sherebangla nagar56']);
// Thana::create(['id'=>'333','name'=>'Tejgoun Industrial Area56']);
// Thana::create(['id'=>'334','name'=>'Mohammadpur56']);
// Thana::create(['id'=>'335','name'=>'Adabor56']);
// Thana::create(['id'=>'336','name'=>'Mirpur56']);
// Thana::create(['id'=>'337','name'=>'Shahali56']);
// Thana::create(['id'=>'338','name'=>'Pollobi56']);
// Thana::create(['id'=>'339','name'=>'Kaprul56']);
// Thana::create(['id'=>'340','name'=>'Darus salam56']);
// Thana::create(['id'=>'341','name'=>'Gulshan56']);
// Thana::create(['id'=>'342','name'=>'Badda56']);
// Thana::create(['id'=>'343','name'=>'Cantonment56']);
// Thana::create(['id'=>'344','name'=>'Kilket56']);
// Thana::create(['id'=>'345','name'=>'Uttara56']);
// Thana::create(['id'=>'346','name'=>'Turag56']);
// Thana::create(['id'=>'347','name'=>'Uttar khan56']);
// Thana::create(['id'=>'348','name'=>'Dakkin khan56']);
// Thana::create(['id'=>'349','name'=>'Biman bandar56']);
// Thana::create(['id'=>'350','name'=>'Sirajganj Sadar94']);
// Thana::create(['id'=>'351','name'=>'Belkuchi94']);
// Thana::create(['id'=>'352','name'=>'Chauhali94']);
// Thana::create(['id'=>'353','name'=>'Kamarkhanda94']);
// Thana::create(['id'=>'354','name'=>'Kazipur94']);
// Thana::create(['id'=>'355','name'=>'Raiganj94']);
// Thana::create(['id'=>'356','name'=>'Shahjadpur94']);
// Thana::create(['id'=>'357','name'=>'Tarash94']);
// Thana::create(['id'=>'358','name'=>'Ullahpara94']);
// Thana::create(['id'=>'359','name'=>'Ashulia56']);
// Thana::create(['id'=>'360','name'=>'Savar56']);
// Thana::create(['id'=>'361','name'=>'Keranigonj56']);
// Thana::create(['id'=>'362','name'=>'South Keranigonj56']);
// Thana::create(['id'=>'363','name'=>'Birampur84']);
// Thana::create(['id'=>'364','name'=>'Birganj84']);
// Thana::create(['id'=>'365','name'=>'Biral84']);
// Thana::create(['id'=>'366','name'=>'Bochaganj84']);
// Thana::create(['id'=>'367','name'=>'Chirirbandar84']);
// Thana::create(['id'=>'368','name'=>'Phulbari84']);
// Thana::create(['id'=>'369','name'=>'Ghoraghat84']);
// Thana::create(['id'=>'370','name'=>'Hakimpur84']);
// Thana::create(['id'=>'371','name'=>'Kaharole84']);
// Thana::create(['id'=>'372','name'=>'Khansama84']);
// Thana::create(['id'=>'373','name'=>'Dinajpur Sadar84']);
// Thana::create(['id'=>'374','name'=>'Nawabganj84']);
// Thana::create(['id'=>'375','name'=>'Parbatipur84']);
// Thana::create(['id'=>'376','name'=>'Parbatipur84']);
// Thana::create(['id'=>'377','name'=>'Fulchhari85']);
// Thana::create(['id'=>'378','name'=>'Gaibandha sadar85']);
// Thana::create(['id'=>'379','name'=>'Gobindaganj85']);
// Thana::create(['id'=>'380','name'=>'Palashbari85']);
// Thana::create(['id'=>'381','name'=>'Sadullapur85']);
// Thana::create(['id'=>'382','name'=>'Saghata85']);
// Thana::create(['id'=>'383','name'=>'Sundarganj85']);
// Thana::create(['id'=>'384','name'=>'Kurigram Sadar83']);
// Thana::create(['id'=>'385','name'=>'Nageswari83']);
// Thana::create(['id'=>'386','name'=>'Bhurungamari83']);
// Thana::create(['id'=>'387','name'=>'Phulbari83']);
// Thana::create(['id'=>'388','name'=>'Rajarhat83']);
// Thana::create(['id'=>'389','name'=>'Ulipur83']);
// Thana::create(['id'=>'390','name'=>'Chilmari83']);
// Thana::create(['id'=>'391','name'=>'Rowmari83']);
// Thana::create(['id'=>'392','name'=>'Char Rajibpur83']);
// Thana::create(['id'=>'393','name'=>'Char Rajibpur83']);
// Thana::create(['id'=>'394','name'=>'Lalmanirhat Sadar113']);
// Thana::create(['id'=>'395','name'=>'Aditmari113']);
// Thana::create(['id'=>'396','name'=>'Kaliganj113']);
// Thana::create(['id'=>'397','name'=>'Hatibandha113']);
// Thana::create(['id'=>'398','name'=>'Patgram113']);
// Thana::create(['id'=>'399','name'=>'Nilphamari Sadar82']);
// Thana::create(['id'=>'400','name'=>'Saidpur82']);
// Thana::create(['id'=>'401','name'=>'Jaldhaka82']);
// Thana::create(['id'=>'402','name'=>'Kishoreganj82']);
// Thana::create(['id'=>'403','name'=>'Domar82']);
// Thana::create(['id'=>'404','name'=>'Dimla82']);
// Thana::create(['id'=>'405','name'=>'Panchagarh Sadar80']);
// Thana::create(['id'=>'406','name'=>'Debiganj80']);
// Thana::create(['id'=>'407','name'=>'Boda80']);
// Thana::create(['id'=>'408','name'=>'Atwari80']);
// Thana::create(['id'=>'409','name'=>'Tetulia80']);
// Thana::create(['id'=>'410','name'=>'Badarganj86']);
// Thana::create(['id'=>'411','name'=>'Mithapukur86']);
// Thana::create(['id'=>'412','name'=>'Gangachara86']);
// Thana::create(['id'=>'413','name'=>'Kaunia86']);
// Thana::create(['id'=>'414','name'=>'Rangpur Sadar86']);
// Thana::create(['id'=>'415','name'=>'Pirgachha86']);
// Thana::create(['id'=>'416','name'=>'Pirganj86']);
// Thana::create(['id'=>'417','name'=>'Taraganj86']);
// Thana::create(['id'=>'418','name'=>'Thakurgaon Sadar81']);
// Thana::create(['id'=>'419','name'=>'Pirganj81']);
// Thana::create(['id'=>'420','name'=>'Baliadangi81']);
// Thana::create(['id'=>'421','name'=>'Haripur81']);
// Thana::create(['id'=>'422','name'=>'Ranisankail81']);
// Thana::create(['id'=>'423','name'=>'Ajmiriganj67']);
// Thana::create(['id'=>'424','name'=>'Baniachang67']);
// Thana::create(['id'=>'425','name'=>'Bahubal67']);
// Thana::create(['id'=>'426','name'=>'Chunarughat67']);
// Thana::create(['id'=>'427','name'=>'Habiganj Sadar67']);
// Thana::create(['id'=>'428','name'=>'Lakhai67']);
// Thana::create(['id'=>'429','name'=>'Madhabpur67']);
// Thana::create(['id'=>'430','name'=>'Nabiganj67']);
// Thana::create(['id'=>'431','name'=>'Shaistagonj67']);
// Thana::create(['id'=>'432','name'=>'Moulvibazar Sadar68']);
// Thana::create(['id'=>'433','name'=>'Barlekha68']);
// Thana::create(['id'=>'434','name'=>'Juri68']);
// Thana::create(['id'=>'435','name'=>'Kamalganj68']);
// Thana::create(['id'=>'436','name'=>'Kulaura68']);
// Thana::create(['id'=>'437','name'=>'Rajnagar68']);
// Thana::create(['id'=>'438','name'=>'Sreemangal68']);
// Thana::create(['id'=>'439','name'=>'Bishwamvarpur66']);
// Thana::create(['id'=>'440','name'=>'Chhatak66']);
// Thana::create(['id'=>'441','name'=>'Derai66']);
// Thana::create(['id'=>'442','name'=>'Dharampasha66']);
// Thana::create(['id'=>'443','name'=>'Dowarabazar66']);
// Thana::create(['id'=>'444','name'=>'Jagannathpur66']);
// Thana::create(['id'=>'445','name'=>'Jamalganj66']);
// Thana::create(['id'=>'446','name'=>'Sulla66']);
// Thana::create(['id'=>'447','name'=>'Sunamganj Sadar66']);
// Thana::create(['id'=>'448','name'=>'Tahirpur66']);
// Thana::create(['id'=>'449','name'=>'Balaganj65']);
// Thana::create(['id'=>'450','name'=>'Beanibazar65']);
// Thana::create(['id'=>'451','name'=>'Bishwanath65']);
// Thana::create(['id'=>'452','name'=>'Companiganj65']);
// Thana::create(['id'=>'453','name'=>'Fenchuganj65']);
// Thana::create(['id'=>'454','name'=>'Golapganj65']);
// Thana::create(['id'=>'455','name'=>'Gowainghat65']);
// Thana::create(['id'=>'456','name'=>'Jaintiapur65']);
// Thana::create(['id'=>'457','name'=>'Kanaighat65']);
// Thana::create(['id'=>'458','name'=>'Sylhet Sadar65']);
// Thana::create(['id'=>'459','name'=>'Zakiganj65']);
// Thana::create(['id'=>'460','name'=>'Cox\'s Bazar Sadar79']);
// Thana::create(['id'=>'461','name'=>'Kutubdia79']);
// Thana::create(['id'=>'462','name'=>'Moheskhali79']);
// Thana::create(['id'=>'463','name'=>'Ramu79']);
// Thana::create(['id'=>'464','name'=>'Chakaria79']);
// Thana::create(['id'=>'465','name'=>'Ukia79']);
// Thana::create(['id'=>'466','name'=>'Teknaf79']);
// Thana::create(['id'=>'467','name'=>'Barohatta64']);
// Thana::create(['id'=>'468','name'=>'Kandua64']);
// Thana::create(['id'=>'469','name'=>'Astogram59']);
// Thana::create(['id'=>'475','name'=>'Anowara116']);
// Thana::create(['id'=>'476','name'=>'Banshkhali116']);
// Thana::create(['id'=>'478','name'=>'Langalcoat70']);
// Thana::create(['id'=>'479','name'=>'Chandpur Sadar71']);
// Thana::create(['id'=>'480','name'=>'Matlob North71']);
// Thana::create(['id'=>'481','name'=>'Matlob South71']);
// Thana::create(['id'=>'482','name'=>'Hajigonj71']);
// Thana::create(['id'=>'483','name'=>'Faridgonj71']);
// Thana::create(['id'=>'484','name'=>'Kachua71']);
// Thana::create(['id'=>'485','name'=>'Haimchar71']);
// Thana::create(['id'=>'486','name'=>'Shahrasti71']);
// Thana::create(['id'=>'487','name'=>'Naikhnchhri78']);
// Thana::create(['id'=>'488','name'=>'Lama78']);
// Thana::create(['id'=>'489','name'=>'Alikdom78']);
// Thana::create(['id'=>'490','name'=>'Royanchhri78']);
// Thana::create(['id'=>'491','name'=>'Thanchi78']);
// Thana::create(['id'=>'492','name'=>'Ruma78']);
// Thana::create(['id'=>'493','name'=>'Bandarnbab Sudar78']);
// Thana::create(['id'=>'494','name'=>'Bandarnbab Sudar78']);
// Thana::create(['id'=>'495','name'=>'Bandarnban Sudar78']);
// Thana::create(['id'=>'496','name'=>'Bandarnban Sudar78']);
// Thana::create(['id'=>'497','name'=>'Subornochar72']);
// Thana::create(['id'=>'498','name'=>'Kobirhat72']);
// Thana::create(['id'=>'499','name'=>'Kobirhat72']);
// Thana::create(['id'=>'500','name'=>'B-baria Sadar69']);
// Thana::create(['id'=>'501','name'=>'Bancharampur69']);
// Thana::create(['id'=>'502','name'=>'Nabi nagar69']);
// Thana::create(['id'=>'503','name'=>'Kasba69']);
// Thana::create(['id'=>'504','name'=>'Akhaura69']);
// Thana::create(['id'=>'505','name'=>'Nachhir nagar69']);
// Thana::create(['id'=>'506','name'=>'Sarail69']);
// Thana::create(['id'=>'507','name'=>'Ashugonj69']);
// Thana::create(['id'=>'508','name'=>'Pekua79']);
// Thana::create(['id'=>'509','name'=>'Jashore Sadar101']);
// Thana::create(['id'=>'510','name'=>'Baghar par101']);
// Thana::create(['id'=>'511','name'=>'Avoynagar101']);
// Thana::create(['id'=>'512','name'=>'Kashabpur101']);
// Thana::create(['id'=>'513','name'=>'Monirampur101']);
// Thana::create(['id'=>'514','name'=>'Jikorgchha101']);
// Thana::create(['id'=>'515','name'=>'Chougchha101']);
// Thana::create(['id'=>'516','name'=>'Sharsha101']);
// Thana::create(['id'=>'517','name'=>'Chuwadanga Sudar97']);
// Thana::create(['id'=>'518','name'=>'Alomdanga97']);
// Thana::create(['id'=>'519','name'=>'Damurhuda97']);
// Thana::create(['id'=>'520','name'=>'Jibonnagar97']);
// Thana::create(['id'=>'521','name'=>'Jibonnagar97']);
// Thana::create(['id'=>'522','name'=>'Jhenaiga Sudar98']);
// Thana::create(['id'=>'523','name'=>'Kaliganj98']);
// Thana::create(['id'=>'524','name'=>'Shylkupa98']);
// Thana::create(['id'=>'525','name'=>'Kutchadpur98']);
// Thana::create(['id'=>'526','name'=>'Mohashpur98']);
// Thana::create(['id'=>'527','name'=>'Horinakundu98']);
// Thana::create(['id'=>'528','name'=>'Horinakundu98']);
// Thana::create(['id'=>'529','name'=>'Borishal Sudar106']);
// Thana::create(['id'=>'530','name'=>'Bakargonj106']);
// Thana::create(['id'=>'531','name'=>'Ujirpur106']);
// Thana::create(['id'=>'532','name'=>'Babugonj106']);
// Thana::create(['id'=>'533','name'=>'Mahandigonj106']);
// Thana::create(['id'=>'534','name'=>'Hijla106']);
// Thana::create(['id'=>'535','name'=>'Moladi106']);
// Thana::create(['id'=>'536','name'=>'Banaripara106']);
// Thana::create(['id'=>'537','name'=>'Agoiljhara106']);
// Thana::create(['id'=>'538','name'=>'Gouranadi106']);
// Thana::create(['id'=>'540','name'=>'Potuwakhali Sudar110']);
// Thana::create(['id'=>'541','name'=>'Baufol110']);
// Thana::create(['id'=>'542','name'=>'Doshmina110']);
// Thana::create(['id'=>'543','name'=>'Golachipa110']);
// Thana::create(['id'=>'544','name'=>'Kulapara110']);
// Thana::create(['id'=>'545','name'=>'Mirzagonj110']);
// Thana::create(['id'=>'547','name'=>'Dumki110']);
// Thana::create(['id'=>'548','name'=>'Jhalokhati Sudar108']);
// Thana::create(['id'=>'549','name'=>'Nolchhiti108']);
// Thana::create(['id'=>'550','name'=>'Rajapur108']);
// Thana::create(['id'=>'551','name'=>'Kathalia108']);
// Thana::create(['id'=>'552','name'=>'Charfashon111']);
// Thana::create(['id'=>'553','name'=>'Lalmuhon111']);
// Thana::create(['id'=>'554','name'=>'Monpura111']);
// Thana::create(['id'=>'555','name'=>'Tujomuddin111']);
// Thana::create(['id'=>'556','name'=>'Borhanuddin111']);
// Thana::create(['id'=>'557','name'=>'Bhula Sudar111']);
// Thana::create(['id'=>'558','name'=>'Dhultkhan111']);
// Thana::create(['id'=>'559','name'=>'Najirpur107']);
// Thana::create(['id'=>'560','name'=>'Nachharabad107']);
// Thana::create(['id'=>'561','name'=>'Kawkhali107']);
// Thana::create(['id'=>'562','name'=>'Piroj pur Sudar107']);
// Thana::create(['id'=>'563','name'=>'Vhandaria107']);
// Thana::create(['id'=>'564','name'=>'Mothbaria107']);
// Thana::create(['id'=>'565','name'=>'Jiyanagar107']);
// Thana::create(['id'=>'566','name'=>'Amtoli109']);
// Thana::create(['id'=>'567','name'=>'Betagi109']);
// Thana::create(['id'=>'568','name'=>'Bamna109']);
// Thana::create(['id'=>'569','name'=>'Patarghata109']);
// Thana::create(['id'=>'570','name'=>'Barguna sadar109']);
// Thana::create(['id'=>'571','name'=>'South surma65']);
// Thana::create(['id'=>'572','name'=>'South sunamganj66']);
// Thana::create(['id'=>'573','name'=>'Chand gaon116']);
// Thana::create(['id'=>'574','name'=>'Chittagram bondor116']);
// Thana::create(['id'=>'575','name'=>'kotyalee101']);


    }
}
