<?php

use Illuminate\Database\Seeder;
use App\Model\Thana;

class ThanaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Thana::create(['id'=>'7','district_id'=>'49','name'=>'Faridpur Sadar']);
Thana::create(['id'=>'8','district_id'=>'49','name'=>'Saltha']);
Thana::create(['id'=>'9','district_id'=>'49','name'=>'Nagarkanda']);
Thana::create(['id'=>'10','district_id'=>'49','name'=>'Alfadanga']);
Thana::create(['id'=>'11','district_id'=>'49','name'=>'Bowalmari']);
Thana::create(['id'=>'12','district_id'=>'49','name'=>'Modhukhali']);
Thana::create(['id'=>'13','district_id'=>'49','name'=>'Vanga']);
Thana::create(['id'=>'14','district_id'=>'49','name'=>'Sadarpur']);
Thana::create(['id'=>'16','district_id'=>'50','name'=>'Rajbari Sadar']);
Thana::create(['id'=>'17','district_id'=>'50','name'=>'Guwalando']);
Thana::create(['id'=>'18','district_id'=>'50','name'=>'Pangsha']);
Thana::create(['id'=>'19','district_id'=>'50','name'=>'Baliyakandi']);
Thana::create(['id'=>'20','district_id'=>'105','name'=>'Gopalgonj Sadar']);
Thana::create(['id'=>'21','district_id'=>'105','name'=>'Kotalipara']);
Thana::create(['id'=>'22','district_id'=>'105','name'=>'Tongi para']);
Thana::create(['id'=>'23','district_id'=>'105','name'=>'Muksod pur']);
Thana::create(['id'=>'24','district_id'=>'105','name'=>'Kashiyani']);
Thana::create(['id'=>'25','district_id'=>'99','name'=>'Magura Sadar']);
Thana::create(['id'=>'26','district_id'=>'99','name'=>'Sripur']);
Thana::create(['id'=>'27','district_id'=>'99','name'=>'Shalikha']);
Thana::create(['id'=>'28','district_id'=>'99','name'=>'Mohammadpur']);
Thana::create(['id'=>'29','district_id'=>'116','name'=>'Boalkhali']);
Thana::create(['id'=>'34','district_id'=>'116','name'=>'Chandanaish']);
Thana::create(['id'=>'35','district_id'=>'116','name'=>'Fatikchhari']);
Thana::create(['id'=>'36','district_id'=>'116','name'=>'Hathazari']);
Thana::create(['id'=>'37','district_id'=>'116','name'=>'Lohagara']);
Thana::create(['id'=>'38','district_id'=>'116','name'=>'Mirsharai']);
Thana::create(['id'=>'39','district_id'=>'116','name'=>'Patiya']);
Thana::create(['id'=>'40','district_id'=>'116','name'=>'Rangunia']);
Thana::create(['id'=>'41','district_id'=>'116','name'=>'Raozan']);
Thana::create(['id'=>'42','district_id'=>'116','name'=>'Sandwip']);
Thana::create(['id'=>'43','district_id'=>'116','name'=>'Satkania']);
Thana::create(['id'=>'44','district_id'=>'116','name'=>'Sitakunda']);
Thana::create(['id'=>'45','district_id'=>'70','name'=>'Barura']);
Thana::create(['id'=>'46','district_id'=>'70','name'=>'Brahmanpara']);
Thana::create(['id'=>'47','district_id'=>'70','name'=>'Burichong']);
Thana::create(['id'=>'48','district_id'=>'70','name'=>'Chandina']);
Thana::create(['id'=>'49','district_id'=>'70','name'=>'Chauddagram']);
Thana::create(['id'=>'50','district_id'=>'70','name'=>'Daudkandi']);
Thana::create(['id'=>'51','district_id'=>'70','name'=>'Debidwar']);
Thana::create(['id'=>'52','district_id'=>'70','name'=>'Homna']);
Thana::create(['id'=>'53','district_id'=>'70','name'=>'Comilla Adarsa Sadar']);
Thana::create(['id'=>'54','district_id'=>'70','name'=>'Laksam']);
Thana::create(['id'=>'55','district_id'=>'70','name'=>'Monohorgonj']);
Thana::create(['id'=>'56','district_id'=>'70','name'=>'Meghna']);
Thana::create(['id'=>'57','district_id'=>'70','name'=>'Muradnagar']);
Thana::create(['id'=>'58','district_id'=>'70','name'=>'Nangalkot']);
Thana::create(['id'=>'59','district_id'=>'70','name'=>'Comilla Sadar South']);
Thana::create(['id'=>'60','district_id'=>'70','name'=>'Titas']);
Thana::create(['id'=>'61','district_id'=>'74','name'=>'Feni sadar']);
Thana::create(['id'=>'62','district_id'=>'74','name'=>'Chagalnaiya']);
Thana::create(['id'=>'63','district_id'=>'74','name'=>'Daganbhyan']);
Thana::create(['id'=>'64','district_id'=>'74','name'=>'Parshuram']);
Thana::create(['id'=>'65','district_id'=>'74','name'=>'Fhulgazi']);
Thana::create(['id'=>'66','district_id'=>'74','name'=>'Sonagazi']);
Thana::create(['id'=>'67','district_id'=>'76','name'=>'Dighinala']);
Thana::create(['id'=>'68','district_id'=>'76','name'=>'Khagrachhari']);
Thana::create(['id'=>'69','district_id'=>'76','name'=>'Lakshmichhari']);
Thana::create(['id'=>'70','district_id'=>'76','name'=>'Mahalchhari']);
Thana::create(['id'=>'71','district_id'=>'76','name'=>'Manikchhari']);
Thana::create(['id'=>'72','district_id'=>'76','name'=>'Matiranga']);
Thana::create(['id'=>'73','district_id'=>'76','name'=>'Panchhar']);
Thana::create(['id'=>'74','district_id'=>'76','name'=>'Ramgarh']);
Thana::create(['id'=>'75','district_id'=>'73','name'=>'Laxmipur Sadar']);
Thana::create(['id'=>'76','district_id'=>'73','name'=>'Raipur']);
Thana::create(['id'=>'77','district_id'=>'73','name'=>'Ramganj']);
Thana::create(['id'=>'78','district_id'=>'73','name'=>'Ramgati']);
Thana::create(['id'=>'79','district_id'=>'73','name'=>'Komol Nagar']);
Thana::create(['id'=>'80','district_id'=>'72','name'=>'Begumganj']);
Thana::create(['id'=>'81','district_id'=>'72','name'=>'Chatkhil']);
Thana::create(['id'=>'82','district_id'=>'72','name'=>'Companiganj']);
Thana::create(['id'=>'83','district_id'=>'72','name'=>'Hatiya']);
Thana::create(['id'=>'84','district_id'=>'72','name'=>'Noakhali Sadar']);
Thana::create(['id'=>'85','district_id'=>'72','name'=>'Senbagh']);
Thana::create(['id'=>'86','district_id'=>'72','name'=>'Sonaimuri']);
Thana::create(['id'=>'87','district_id'=>'77','name'=>'Rangamati Sadar']);
Thana::create(['id'=>'88','district_id'=>'77','name'=>'Belaichhari']);
Thana::create(['id'=>'89','district_id'=>'77','name'=>'Bagaichhari']);
Thana::create(['id'=>'90','district_id'=>'77','name'=>'Barkal']);
Thana::create(['id'=>'91','district_id'=>'77','name'=>'Juraichhari']);
Thana::create(['id'=>'92','district_id'=>'77','name'=>'Rajasthali']);
Thana::create(['id'=>'93','district_id'=>'77','name'=>'Kaptai']);
Thana::create(['id'=>'94','district_id'=>'77','name'=>'Langadu']);
Thana::create(['id'=>'95','district_id'=>'77','name'=>'Nannerchar']);
Thana::create(['id'=>'96','district_id'=>'77','name'=>'Kaukhali']);
Thana::create(['id'=>'97','district_id'=>'56','name'=>'Dohar']);
Thana::create(['id'=>'98','district_id'=>'56','name'=>'Dhamrai']);
Thana::create(['id'=>'99','district_id'=>'56','name'=>'Nawabgonj']);
Thana::create(['id'=>'100','district_id'=>'58','name'=>'Gazipur Sadar']);
Thana::create(['id'=>'101','district_id'=>'58','name'=>'Joydebpur']);
Thana::create(['id'=>'102','district_id'=>'58','name'=>'Kaliakior']);
Thana::create(['id'=>'103','district_id'=>'58','name'=>'Kapasia']);
Thana::create(['id'=>'104','district_id'=>'58','name'=>'Sripur']);
Thana::create(['id'=>'105','district_id'=>'58','name'=>'Kaliganj']);
Thana::create(['id'=>'106','district_id'=>'58','name'=>'Tongi']);
Thana::create(['id'=>'107','district_id'=>'62','name'=>'Dewanganj']);
Thana::create(['id'=>'108','district_id'=>'62','name'=>'Baksiganj']);
Thana::create(['id'=>'109','district_id'=>'62','name'=>'Islampur']);
Thana::create(['id'=>'110','district_id'=>'62','name'=>'Jamalpur Sadar']);
Thana::create(['id'=>'111','district_id'=>'62','name'=>'Madarganj']);
Thana::create(['id'=>'112','district_id'=>'62','name'=>'Melandaha']);
Thana::create(['id'=>'113','district_id'=>'62','name'=>'Sarishabari']);
Thana::create(['id'=>'114','district_id'=>'59','name'=>'Astagram']);
Thana::create(['id'=>'115','district_id'=>'59','name'=>'Bajitpur']);
Thana::create(['id'=>'116','district_id'=>'59','name'=>'Bhairab']);
Thana::create(['id'=>'117','district_id'=>'59','name'=>'Hossainpur']);
Thana::create(['id'=>'118','district_id'=>'59','name'=>'Itna']);
Thana::create(['id'=>'119','district_id'=>'59','name'=>'Karimganj']);
Thana::create(['id'=>'120','district_id'=>'59','name'=>'Katiadi']);
Thana::create(['id'=>'121','district_id'=>'59','name'=>'Kishoreganj Sadar']);
Thana::create(['id'=>'122','district_id'=>'59','name'=>'Kuliarchar']);
Thana::create(['id'=>'123','district_id'=>'59','name'=>'Mithamain']);
Thana::create(['id'=>'124','district_id'=>'59','name'=>'Nikli']);
Thana::create(['id'=>'125','district_id'=>'59','name'=>'Pakundia']);
Thana::create(['id'=>'126','district_id'=>'59','name'=>'Tarail']);
Thana::create(['id'=>'127','district_id'=>'52','name'=>'Madaripur Sadar']);
Thana::create(['id'=>'128','district_id'=>'52','name'=>'Kalkini']);
Thana::create(['id'=>'129','district_id'=>'52','name'=>'Rajoir']);
Thana::create(['id'=>'130','district_id'=>'52','name'=>'shibchar']);
Thana::create(['id'=>'131','district_id'=>'54','name'=>'Manikganj Sadar']);
Thana::create(['id'=>'132','district_id'=>'54','name'=>'Singair']);
Thana::create(['id'=>'133','district_id'=>'54','name'=>'Shivalaya']);
Thana::create(['id'=>'134','district_id'=>'54','name'=>'Saturia']);
Thana::create(['id'=>'135','district_id'=>'54','name'=>'Harirampur']);
Thana::create(['id'=>'136','district_id'=>'54','name'=>'Ghior']);
Thana::create(['id'=>'137','district_id'=>'54','name'=>'Daulatpur']);
Thana::create(['id'=>'138','district_id'=>'55','name'=>'Lohajang']);
Thana::create(['id'=>'139','district_id'=>'55','name'=>'Sreenagar']);
Thana::create(['id'=>'140','district_id'=>'55','name'=>'Munshiganj Sadar']);
Thana::create(['id'=>'141','district_id'=>'55','name'=>'Sirajdikhan']);
Thana::create(['id'=>'142','district_id'=>'55','name'=>'Tongibari']);
Thana::create(['id'=>'143','district_id'=>'55','name'=>'Gazaria']);
Thana::create(['id'=>'144','district_id'=>'60','name'=>'Bhaluka']);
Thana::create(['id'=>'145','district_id'=>'60','name'=>'Trishal']);
Thana::create(['id'=>'146','district_id'=>'60','name'=>'Haluaghat']);
Thana::create(['id'=>'147','district_id'=>'60','name'=>'Muktagachha']);
Thana::create(['id'=>'148','district_id'=>'60','name'=>'Dhobaura']);
Thana::create(['id'=>'150','district_id'=>'60','name'=>'Gaffargaon']);
Thana::create(['id'=>'151','district_id'=>'60','name'=>'Gauripur']);
Thana::create(['id'=>'152','district_id'=>'60','name'=>'Ishwarganj']);
Thana::create(['id'=>'153','district_id'=>'60','name'=>'Mymensingh Sadar']);
Thana::create(['id'=>'154','district_id'=>'60','name'=>'Nandail']);
Thana::create(['id'=>'155','district_id'=>'60','name'=>'Phulpur']);
Thana::create(['id'=>'156','district_id'=>'57','name'=>'Araihazar']);
Thana::create(['id'=>'157','district_id'=>'57','name'=>'Sonargaon']);
Thana::create(['id'=>'158','district_id'=>'57','name'=>'Bandar']);
Thana::create(['id'=>'159','district_id'=>'57','name'=>'Naryanganj Sadar']);
Thana::create(['id'=>'160','district_id'=>'57','name'=>'Rupganj']);
Thana::create(['id'=>'161','district_id'=>'57','name'=>'Siddirgonj']);
Thana::create(['id'=>'162','district_id'=>'57','name'=>'Siddirgonj']);
Thana::create(['id'=>'163','district_id'=>'112','name'=>'Belabo']);
Thana::create(['id'=>'164','district_id'=>'112','name'=>'Monohardi']);
Thana::create(['id'=>'165','district_id'=>'112','name'=>'Narsingdi Sadar']);
Thana::create(['id'=>'166','district_id'=>'112','name'=>'Palash']);
Thana::create(['id'=>'167','district_id'=>'112','name'=>'Raipura']);
Thana::create(['id'=>'168','district_id'=>'112','name'=>'Shibpur']);
Thana::create(['id'=>'169','district_id'=>'64','name'=>'Durgapur']);
Thana::create(['id'=>'171','district_id'=>'64','name'=>'Kalmakanda']);
Thana::create(['id'=>'172','district_id'=>'64','name'=>'Purbadhala']);
Thana::create(['id'=>'173','district_id'=>'64','name'=>'Netrokona Sadar']);
Thana::create(['id'=>'174','district_id'=>'64','name'=>'Atpara']);
Thana::create(['id'=>'175','district_id'=>'64','name'=>'Mohongonj']);
Thana::create(['id'=>'177','district_id'=>'64','name'=>'Madan']);
Thana::create(['id'=>'178','district_id'=>'64','name'=>'Khaliajuri']);
Thana::create(['id'=>'179','district_id'=>'53','name'=>'Shariatpur']);
Thana::create(['id'=>'180','district_id'=>'53','name'=>'Damudya']);
Thana::create(['id'=>'181','district_id'=>'53','name'=>'Naria']);
Thana::create(['id'=>'182','district_id'=>'53','name'=>'Jajira']);
Thana::create(['id'=>'183','district_id'=>'53','name'=>'Bhedarganj']);
Thana::create(['id'=>'184','district_id'=>'53','name'=>'Gosairhat']);
Thana::create(['id'=>'185','district_id'=>'53','name'=>'Shakhipur']);
Thana::create(['id'=>'186','district_id'=>'63','name'=>'Jhenaigati']);
Thana::create(['id'=>'187','district_id'=>'63','name'=>'Nakla']);
Thana::create(['id'=>'188','district_id'=>'63','name'=>'Nalitabari']);
Thana::create(['id'=>'189','district_id'=>'63','name'=>'Sherpur Sadar']);
Thana::create(['id'=>'190','district_id'=>'63','name'=>'Sreebardi']);
Thana::create(['id'=>'191','district_id'=>'61','name'=>'Tangail Sadar']);
Thana::create(['id'=>'192','district_id'=>'61','name'=>'Sakhipur']);
Thana::create(['id'=>'193','district_id'=>'61','name'=>'Basail']);
Thana::create(['id'=>'194','district_id'=>'61','name'=>'Madhupur']);
Thana::create(['id'=>'195','district_id'=>'61','name'=>'Ghatail']);
Thana::create(['id'=>'196','district_id'=>'61','name'=>'Kalihati']);
Thana::create(['id'=>'197','district_id'=>'61','name'=>'Nagarpur']);
Thana::create(['id'=>'198','district_id'=>'61','name'=>'Mirzapur']);
Thana::create(['id'=>'199','district_id'=>'61','name'=>'Gopalpur']);
Thana::create(['id'=>'200','district_id'=>'61','name'=>'Delduar']);
Thana::create(['id'=>'201','district_id'=>'61','name'=>'Bhuapur']);
Thana::create(['id'=>'202','district_id'=>'61','name'=>'Dhonbari']);
Thana::create(['id'=>'203','district_id'=>'104','name'=>'Bagerhat Sadar']);
Thana::create(['id'=>'204','district_id'=>'104','name'=>'Chitalmari']);
Thana::create(['id'=>'205','district_id'=>'104','name'=>'Fakirhat']);
Thana::create(['id'=>'206','district_id'=>'104','name'=>'Kachua']);
Thana::create(['id'=>'207','district_id'=>'104','name'=>'Mollahat']);
Thana::create(['id'=>'208','district_id'=>'104','name'=>'Mongla']);
Thana::create(['id'=>'209','district_id'=>'104','name'=>'Morrelganj']);
Thana::create(['id'=>'210','district_id'=>'104','name'=>'Rampal']);
Thana::create(['id'=>'211','district_id'=>'104','name'=>'Sarankhola']);
Thana::create(['id'=>'212','district_id'=>'49','name'=>'Char vodrashon']);
Thana::create(['id'=>'215','district_id'=>'93','name'=>'Iswardi']);
Thana::create(['id'=>'217','district_id'=>'103','name'=>'Terokhada']);
Thana::create(['id'=>'218','district_id'=>'103','name'=>'Batiaghata']);
Thana::create(['id'=>'219','district_id'=>'103','name'=>'Dacope']);
Thana::create(['id'=>'220','district_id'=>'103','name'=>'Dumuria']);
Thana::create(['id'=>'221','district_id'=>'103','name'=>'Dighalia']);
Thana::create(['id'=>'222','district_id'=>'103','name'=>'Koyra']);
Thana::create(['id'=>'223','district_id'=>'103','name'=>'Paikgachha']);
Thana::create(['id'=>'224','district_id'=>'103','name'=>'Phultala']);
Thana::create(['id'=>'225','district_id'=>'103','name'=>'Rupsa']);
Thana::create(['id'=>'226','district_id'=>'95','name'=>'Kushtia Sadar']);
Thana::create(['id'=>'227','district_id'=>'95','name'=>'Kumarkhali']);
Thana::create(['id'=>'228','district_id'=>'95','name'=>'Daulatpur']);
Thana::create(['id'=>'229','district_id'=>'95','name'=>'Mirpur']);
Thana::create(['id'=>'230','district_id'=>'95','name'=>'Bheramara']);
Thana::create(['id'=>'231','district_id'=>'95','name'=>'Khoksa']);
Thana::create(['id'=>'232','district_id'=>'99','name'=>'Magura Sadar']);
Thana::create(['id'=>'233','district_id'=>'99','name'=>'Mohammadpur']);
Thana::create(['id'=>'234','district_id'=>'99','name'=>'Shalikha']);
Thana::create(['id'=>'235','district_id'=>'99','name'=>'Sreepur']);
Thana::create(['id'=>'236','district_id'=>'96','name'=>'Meher pur Sadar']);
Thana::create(['id'=>'237','district_id'=>'96','name'=>'Gangni']);
Thana::create(['id'=>'238','district_id'=>'96','name'=>'Mujib nagar']);
Thana::create(['id'=>'239','district_id'=>'100','name'=>'Narail Sadar']);
Thana::create(['id'=>'240','district_id'=>'100','name'=>'Kalia']);
Thana::create(['id'=>'241','district_id'=>'100','name'=>'Lohagara']);
Thana::create(['id'=>'242','district_id'=>'102','name'=>'Satkhira Sadar']);
Thana::create(['id'=>'243','district_id'=>'102','name'=>'Assasuni']);
Thana::create(['id'=>'244','district_id'=>'102','name'=>'Debhata']);
Thana::create(['id'=>'245','district_id'=>'102','name'=>'Tala']);
Thana::create(['id'=>'246','district_id'=>'102','name'=>'Kalaroa']);
Thana::create(['id'=>'247','district_id'=>'102','name'=>'Kaliganj']);
Thana::create(['id'=>'248','district_id'=>'102','name'=>'Shyamnagar']);
Thana::create(['id'=>'249','district_id'=>'87','name'=>'Adamdighi']);
Thana::create(['id'=>'250','district_id'=>'87','name'=>'Bogra Sadar']);
Thana::create(['id'=>'251','district_id'=>'87','name'=>'Dhunat']);
Thana::create(['id'=>'252','district_id'=>'87','name'=>'Dupchanchia']);
Thana::create(['id'=>'253','district_id'=>'87','name'=>'Gabtali']);
Thana::create(['id'=>'254','district_id'=>'87','name'=>'Kahaloo']);
Thana::create(['id'=>'255','district_id'=>'87','name'=>'Nandigram']);
Thana::create(['id'=>'256','district_id'=>'87','name'=>'Sahajanpur']);
Thana::create(['id'=>'257','district_id'=>'87','name'=>'Sariakandi']);
Thana::create(['id'=>'258','district_id'=>'87','name'=>'Sherpur']);
Thana::create(['id'=>'259','district_id'=>'87','name'=>'Shibganj']);
Thana::create(['id'=>'260','district_id'=>'87','name'=>'Sonatala']);
Thana::create(['id'=>'261','district_id'=>'88','name'=>'Akkelpur']);
Thana::create(['id'=>'262','district_id'=>'88','name'=>'Joypurhat Sadar']);
Thana::create(['id'=>'263','district_id'=>'88','name'=>'Kalai']);
Thana::create(['id'=>'264','district_id'=>'88','name'=>'Khetlal']);
Thana::create(['id'=>'265','district_id'=>'88','name'=>'Panchbibi']);
Thana::create(['id'=>'266','district_id'=>'89','name'=>'Naogaon']);
Thana::create(['id'=>'267','district_id'=>'89','name'=>'Manda']);
Thana::create(['id'=>'268','district_id'=>'89','name'=>'Niamatpur']);
Thana::create(['id'=>'269','district_id'=>'89','name'=>'Atrai']);
Thana::create(['id'=>'270','district_id'=>'89','name'=>'Raninagar']);
Thana::create(['id'=>'271','district_id'=>'89','name'=>'Patnitala']);
Thana::create(['id'=>'272','district_id'=>'89','name'=>'Mahadevpur']);
Thana::create(['id'=>'273','district_id'=>'89','name'=>'Dhamoirhat']);
Thana::create(['id'=>'274','district_id'=>'89','name'=>'Sapahar']);
Thana::create(['id'=>'275','district_id'=>'89','name'=>'Porsha']);
Thana::create(['id'=>'276','district_id'=>'89','name'=>'Badalgachhi']);
Thana::create(['id'=>'277','district_id'=>'92','name'=>'Singra']);
Thana::create(['id'=>'278','district_id'=>'92','name'=>'Boraigram']);
Thana::create(['id'=>'279','district_id'=>'92','name'=>'Gurudaspur']);
Thana::create(['id'=>'280','district_id'=>'92','name'=>'Bagatipara']);
Thana::create(['id'=>'281','district_id'=>'92','name'=>'Lalpur']);
Thana::create(['id'=>'282','district_id'=>'92','name'=>'Natore Sadar']);
Thana::create(['id'=>'283','district_id'=>'92','name'=>'Baraigram']);
Thana::create(['id'=>'284','district_id'=>'90','name'=>'Bholahat']);
Thana::create(['id'=>'285','district_id'=>'90','name'=>'Gomastapur']);
Thana::create(['id'=>'286','district_id'=>'90','name'=>'Nachole']);
Thana::create(['id'=>'287','district_id'=>'90','name'=>'Nawabganj Sadar']);
Thana::create(['id'=>'288','district_id'=>'90','name'=>'Shibganj']);
Thana::create(['id'=>'289','district_id'=>'93','name'=>'Atgharia']);
Thana::create(['id'=>'290','district_id'=>'93','name'=>'Bera']);
Thana::create(['id'=>'291','district_id'=>'93','name'=>'Bhangura']);
Thana::create(['id'=>'292','district_id'=>'93','name'=>'Chatmohar']);
Thana::create(['id'=>'293','district_id'=>'93','name'=>'Faridpur']);
Thana::create(['id'=>'294','district_id'=>'93','name'=>'Ishwardi']);
Thana::create(['id'=>'295','district_id'=>'93','name'=>'Pabna Sadar']);
Thana::create(['id'=>'296','district_id'=>'93','name'=>'Santhia']);
Thana::create(['id'=>'297','district_id'=>'93','name'=>'Sujanagar']);
Thana::create(['id'=>'298','district_id'=>'91','name'=>'Bagha']);
Thana::create(['id'=>'299','district_id'=>'91','name'=>'Bagmara']);
Thana::create(['id'=>'300','district_id'=>'91','name'=>'Charghat']);
Thana::create(['id'=>'301','district_id'=>'91','name'=>'Durgapur']);
Thana::create(['id'=>'302','district_id'=>'91','name'=>'Godagari']);
Thana::create(['id'=>'303','district_id'=>'91','name'=>'Mohanpur']);
Thana::create(['id'=>'304','district_id'=>'91','name'=>'Paba']);
Thana::create(['id'=>'305','district_id'=>'91','name'=>'Puthia']);
Thana::create(['id'=>'306','district_id'=>'91','name'=>'Tanore']);
Thana::create(['id'=>'307','district_id'=>'56','name'=>'Ramna']);
Thana::create(['id'=>'309','district_id'=>'56','name'=>'Dhanmondi']);
Thana::create(['id'=>'310','district_id'=>'56','name'=>'Hajaribag']);
Thana::create(['id'=>'311','district_id'=>'56','name'=>'New market']);
Thana::create(['id'=>'312','district_id'=>'56','name'=>'Shahabag']);
Thana::create(['id'=>'313','district_id'=>'56','name'=>'Kala Bagan']);
Thana::create(['id'=>'314','district_id'=>'56','name'=>'Lal bag']);
Thana::create(['id'=>'315','district_id'=>'56','name'=>'Kotowali']);
Thana::create(['id'=>'316','district_id'=>'56','name'=>'Kamrangirchar']);
Thana::create(['id'=>'317','district_id'=>'56','name'=>'Chalk bazar']);
Thana::create(['id'=>'318','district_id'=>'56','name'=>'Bangshal']);
Thana::create(['id'=>'319','district_id'=>'56','name'=>'Sutrapur']);
Thana::create(['id'=>'320','district_id'=>'56','name'=>'Shampur']);
Thana::create(['id'=>'321','district_id'=>'56','name'=>'Jatrabari']);
Thana::create(['id'=>'322','district_id'=>'56','name'=>'Demra']);
Thana::create(['id'=>'323','district_id'=>'56','name'=>'Kadamtoli']);
Thana::create(['id'=>'324','district_id'=>'56','name'=>'Gendaria']);
Thana::create(['id'=>'325','district_id'=>'56','name'=>'Motijheel']);
Thana::create(['id'=>'326','district_id'=>'56','name'=>'Polton']);
Thana::create(['id'=>'327','district_id'=>'56','name'=>'subojbag']);
Thana::create(['id'=>'329','district_id'=>'56','name'=>'Khilgoun']);
Thana::create(['id'=>'330','district_id'=>'56','name'=>'Rampura']);
Thana::create(['id'=>'331','district_id'=>'56','name'=>'Tejgoun']);
Thana::create(['id'=>'332','district_id'=>'56','name'=>'Sherebangla nagar']);
Thana::create(['id'=>'333','district_id'=>'56','name'=>'Tejgoun Industrial Area']);
Thana::create(['id'=>'334','district_id'=>'56','name'=>'Mohammadpur']);
Thana::create(['id'=>'335','district_id'=>'56','name'=>'Adabor']);
Thana::create(['id'=>'336','district_id'=>'56','name'=>'Mirpur']);
Thana::create(['id'=>'337','district_id'=>'56','name'=>'Shahali']);
Thana::create(['id'=>'338','district_id'=>'56','name'=>'Pollobi']);
Thana::create(['id'=>'339','district_id'=>'56','name'=>'Kaprul']);
Thana::create(['id'=>'340','district_id'=>'56','name'=>'Darus salam']);
Thana::create(['id'=>'341','district_id'=>'56','name'=>'Gulshan']);
Thana::create(['id'=>'342','district_id'=>'56','name'=>'Badda']);
Thana::create(['id'=>'343','district_id'=>'56','name'=>'Cantonment']);
Thana::create(['id'=>'344','district_id'=>'56','name'=>'Kilket']);
Thana::create(['id'=>'345','district_id'=>'56','name'=>'Uttara']);
Thana::create(['id'=>'346','district_id'=>'56','name'=>'Turag']);
Thana::create(['id'=>'347','district_id'=>'56','name'=>'Uttar khan']);
Thana::create(['id'=>'348','district_id'=>'56','name'=>'Dakkin khan']);
Thana::create(['id'=>'349','district_id'=>'56','name'=>'Biman bandar']);
Thana::create(['id'=>'350','district_id'=>'94','name'=>'Sirajganj Sadar']);
Thana::create(['id'=>'351','district_id'=>'94','name'=>'Belkuchi']);
Thana::create(['id'=>'352','district_id'=>'94','name'=>'Chauhali']);
Thana::create(['id'=>'353','district_id'=>'94','name'=>'Kamarkhanda']);
Thana::create(['id'=>'354','district_id'=>'94','name'=>'Kazipur']);
Thana::create(['id'=>'355','district_id'=>'94','name'=>'Raiganj']);
Thana::create(['id'=>'356','district_id'=>'94','name'=>'Shahjadpur']);
Thana::create(['id'=>'357','district_id'=>'94','name'=>'Tarash']);
Thana::create(['id'=>'358','district_id'=>'94','name'=>'Ullahpara']);
Thana::create(['id'=>'359','district_id'=>'56','name'=>'Ashulia']);
Thana::create(['id'=>'360','district_id'=>'56','name'=>'Savar']);
Thana::create(['id'=>'361','district_id'=>'56','name'=>'Keranigonj']);
Thana::create(['id'=>'362','district_id'=>'56','name'=>'South Keranigonj']);
Thana::create(['id'=>'363','district_id'=>'84','name'=>'Birampur']);
Thana::create(['id'=>'364','district_id'=>'84','name'=>'Birganj']);
Thana::create(['id'=>'365','district_id'=>'84','name'=>'Biral']);
Thana::create(['id'=>'366','district_id'=>'84','name'=>'Bochaganj']);
Thana::create(['id'=>'367','district_id'=>'84','name'=>'Chirirbandar']);
Thana::create(['id'=>'368','district_id'=>'84','name'=>'Phulbari']);
Thana::create(['id'=>'369','district_id'=>'84','name'=>'Ghoraghat']);
Thana::create(['id'=>'370','district_id'=>'84','name'=>'Hakimpur']);
Thana::create(['id'=>'371','district_id'=>'84','name'=>'Kaharole']);
Thana::create(['id'=>'372','district_id'=>'84','name'=>'Khansama']);
Thana::create(['id'=>'373','district_id'=>'84','name'=>'Dinajpur Sadar']);
Thana::create(['id'=>'374','district_id'=>'84','name'=>'Nawabganj']);
Thana::create(['id'=>'375','district_id'=>'84','name'=>'Parbatipur']);
Thana::create(['id'=>'376','district_id'=>'84','name'=>'Parbatipur']);
Thana::create(['id'=>'377','district_id'=>'85','name'=>'Fulchhari']);
Thana::create(['id'=>'378','district_id'=>'85','name'=>'Gaibandha sadar']);
Thana::create(['id'=>'379','district_id'=>'85','name'=>'Gobindaganj']);
Thana::create(['id'=>'380','district_id'=>'85','name'=>'Palashbari']);
Thana::create(['id'=>'381','district_id'=>'85','name'=>'Sadullapur']);
Thana::create(['id'=>'382','district_id'=>'85','name'=>'Saghata']);
Thana::create(['id'=>'383','district_id'=>'85','name'=>'Sundarganj']);
Thana::create(['id'=>'384','district_id'=>'83','name'=>'Kurigram Sadar']);
Thana::create(['id'=>'385','district_id'=>'83','name'=>'Nageswari']);
Thana::create(['id'=>'386','district_id'=>'83','name'=>'Bhurungamari']);
Thana::create(['id'=>'387','district_id'=>'83','name'=>'Phulbari']);
Thana::create(['id'=>'388','district_id'=>'83','name'=>'Rajarhat']);
Thana::create(['id'=>'389','district_id'=>'83','name'=>'Ulipur']);
Thana::create(['id'=>'390','district_id'=>'83','name'=>'Chilmari']);
Thana::create(['id'=>'391','district_id'=>'83','name'=>'Rowmari']);
Thana::create(['id'=>'392','district_id'=>'83','name'=>'Char Rajibpur']);
Thana::create(['id'=>'393','district_id'=>'83','name'=>'Char Rajibpur']);
Thana::create(['id'=>'394','district_id'=>'113','name'=>'Lalmanirhat Sadar']);
Thana::create(['id'=>'395','district_id'=>'113','name'=>'Aditmari']);
Thana::create(['id'=>'396','district_id'=>'113','name'=>'Kaliganj']);
Thana::create(['id'=>'397','district_id'=>'113','name'=>'Hatibandha']);
Thana::create(['id'=>'398','district_id'=>'113','name'=>'Patgram']);
Thana::create(['id'=>'399','district_id'=>'82','name'=>'Nilphamari Sadar']);
Thana::create(['id'=>'400','district_id'=>'82','name'=>'Saidpur']);
Thana::create(['id'=>'401','district_id'=>'82','name'=>'Jaldhaka']);
Thana::create(['id'=>'402','district_id'=>'82','name'=>'Kishoreganj']);
Thana::create(['id'=>'403','district_id'=>'82','name'=>'Domar']);
Thana::create(['id'=>'404','district_id'=>'82','name'=>'Dimla']);
Thana::create(['id'=>'405','district_id'=>'80','name'=>'Panchagarh Sadar']);
Thana::create(['id'=>'406','district_id'=>'80','name'=>'Debiganj']);
Thana::create(['id'=>'407','district_id'=>'80','name'=>'Boda']);
Thana::create(['id'=>'408','district_id'=>'80','name'=>'Atwari']);
Thana::create(['id'=>'409','district_id'=>'80','name'=>'Tetulia']);
Thana::create(['id'=>'410','district_id'=>'86','name'=>'Badarganj']);
Thana::create(['id'=>'411','district_id'=>'86','name'=>'Mithapukur']);
Thana::create(['id'=>'412','district_id'=>'86','name'=>'Gangachara']);
Thana::create(['id'=>'413','district_id'=>'86','name'=>'Kaunia']);
Thana::create(['id'=>'414','district_id'=>'86','name'=>'Rangpur Sadar']);
Thana::create(['id'=>'415','district_id'=>'86','name'=>'Pirgachha']);
Thana::create(['id'=>'416','district_id'=>'86','name'=>'Pirganj']);
Thana::create(['id'=>'417','district_id'=>'86','name'=>'Taraganj']);
Thana::create(['id'=>'418','district_id'=>'81','name'=>'Thakurgaon Sadar']);
Thana::create(['id'=>'419','district_id'=>'81','name'=>'Pirganj']);
Thana::create(['id'=>'420','district_id'=>'81','name'=>'Baliadangi']);
Thana::create(['id'=>'421','district_id'=>'81','name'=>'Haripur']);
Thana::create(['id'=>'422','district_id'=>'81','name'=>'Ranisankail']);
Thana::create(['id'=>'423','district_id'=>'67','name'=>'Ajmiriganj']);
Thana::create(['id'=>'424','district_id'=>'67','name'=>'Baniachang']);
Thana::create(['id'=>'425','district_id'=>'67','name'=>'Bahubal']);
Thana::create(['id'=>'426','district_id'=>'67','name'=>'Chunarughat']);
Thana::create(['id'=>'427','district_id'=>'67','name'=>'Habiganj Sadar']);
Thana::create(['id'=>'428','district_id'=>'67','name'=>'Lakhai']);
Thana::create(['id'=>'429','district_id'=>'67','name'=>'Madhabpur']);
Thana::create(['id'=>'430','district_id'=>'67','name'=>'Nabiganj']);
Thana::create(['id'=>'431','district_id'=>'67','name'=>'Shaistagonj']);
Thana::create(['id'=>'432','district_id'=>'68','name'=>'Moulvibazar Sadar']);
Thana::create(['id'=>'433','district_id'=>'68','name'=>'Barlekha']);
Thana::create(['id'=>'434','district_id'=>'68','name'=>'Juri']);
Thana::create(['id'=>'435','district_id'=>'68','name'=>'Kamalganj']);
Thana::create(['id'=>'436','district_id'=>'68','name'=>'Kulaura']);
Thana::create(['id'=>'437','district_id'=>'68','name'=>'Rajnagar']);
Thana::create(['id'=>'438','district_id'=>'68','name'=>'Sreemangal']);
Thana::create(['id'=>'439','district_id'=>'66','name'=>'Bishwamvarpur']);
Thana::create(['id'=>'440','district_id'=>'66','name'=>'Chhatak']);
Thana::create(['id'=>'441','district_id'=>'66','name'=>'Derai']);
Thana::create(['id'=>'442','district_id'=>'66','name'=>'Dharampasha']);
Thana::create(['id'=>'443','district_id'=>'66','name'=>'Dowarabazar']);
Thana::create(['id'=>'444','district_id'=>'66','name'=>'Jagannathpur']);
Thana::create(['id'=>'445','district_id'=>'66','name'=>'Jamalganj']);
Thana::create(['id'=>'446','district_id'=>'66','name'=>'Sulla']);
Thana::create(['id'=>'447','district_id'=>'66','name'=>'Sunamganj Sadar']);
Thana::create(['id'=>'448','district_id'=>'66','name'=>'Tahirpur']);
Thana::create(['id'=>'449','district_id'=>'65','name'=>'Balaganj']);
Thana::create(['id'=>'450','district_id'=>'65','name'=>'Beanibazar']);
Thana::create(['id'=>'451','district_id'=>'65','name'=>'Bishwanath']);
Thana::create(['id'=>'452','district_id'=>'65','name'=>'Companiganj']);
Thana::create(['id'=>'453','district_id'=>'65','name'=>'Fenchuganj']);
Thana::create(['id'=>'454','district_id'=>'65','name'=>'Golapganj']);
Thana::create(['id'=>'455','district_id'=>'65','name'=>'Gowainghat']);
Thana::create(['id'=>'456','district_id'=>'65','name'=>'Jaintiapur']);
Thana::create(['id'=>'457','district_id'=>'65','name'=>'Kanaighat']);
Thana::create(['id'=>'458','district_id'=>'65','name'=>'Sylhet Sadar']);
Thana::create(['id'=>'459','district_id'=>'65','name'=>'Zakiganj']);
Thana::create(['id'=>'460','district_id'=>'79','name'=>'Cox\'s Bazar Sadar']);
Thana::create(['id'=>'461','district_id'=>'79','name'=>'Kutubdia']);
Thana::create(['id'=>'462','district_id'=>'79','name'=>'Moheskhali']);
Thana::create(['id'=>'463','district_id'=>'79','name'=>'Ramu']);
Thana::create(['id'=>'464','district_id'=>'79','name'=>'Chakaria']);
Thana::create(['id'=>'465','district_id'=>'79','name'=>'Ukia']);
Thana::create(['id'=>'466','district_id'=>'79','name'=>'Teknaf']);
Thana::create(['id'=>'467','district_id'=>'64','name'=>'Barohatta']);
Thana::create(['id'=>'468','district_id'=>'64','name'=>'Kandua']);
Thana::create(['id'=>'469','district_id'=>'59','name'=>'Astogram']);
Thana::create(['id'=>'475','district_id'=>'116','name'=>'Anowara']);
Thana::create(['id'=>'476','district_id'=>'116','name'=>'Banshkhali']);
Thana::create(['id'=>'478','district_id'=>'70','name'=>'Langalcoat']);
Thana::create(['id'=>'479','district_id'=>'71','name'=>'Chandpur Sadar']);
Thana::create(['id'=>'480','district_id'=>'71','name'=>'Matlob North']);
Thana::create(['id'=>'481','district_id'=>'71','name'=>'Matlob South']);
Thana::create(['id'=>'482','district_id'=>'71','name'=>'Hajigonj']);
Thana::create(['id'=>'483','district_id'=>'71','name'=>'Faridgonj']);
Thana::create(['id'=>'484','district_id'=>'71','name'=>'Kachua']);
Thana::create(['id'=>'485','district_id'=>'71','name'=>'Haimchar']);
Thana::create(['id'=>'486','district_id'=>'71','name'=>'Shahrasti']);
Thana::create(['id'=>'487','district_id'=>'78','name'=>'Naikhnchhri']);
Thana::create(['id'=>'488','district_id'=>'78','name'=>'Lama']);
Thana::create(['id'=>'489','district_id'=>'78','name'=>'Alikdom']);
Thana::create(['id'=>'490','district_id'=>'78','name'=>'Royanchhri']);
Thana::create(['id'=>'491','district_id'=>'78','name'=>'Thanchi']);
Thana::create(['id'=>'492','district_id'=>'78','name'=>'Ruma']);
Thana::create(['id'=>'493','district_id'=>'78','name'=>'Bandarnbab Sudar']);
Thana::create(['id'=>'494','district_id'=>'78','name'=>'Bandarnbab Sudar']);
Thana::create(['id'=>'495','district_id'=>'78','name'=>'Bandarnban Sudar']);
Thana::create(['id'=>'496','district_id'=>'78','name'=>'Bandarnban Sudar']);
Thana::create(['id'=>'497','district_id'=>'72','name'=>'Subornochar']);
Thana::create(['id'=>'498','district_id'=>'72','name'=>'Kobirhat']);
Thana::create(['id'=>'499','district_id'=>'72','name'=>'Kobirhat']);
Thana::create(['id'=>'500','district_id'=>'69','name'=>'B-baria Sadar']);
Thana::create(['id'=>'501','district_id'=>'69','name'=>'Bancharampur']);
Thana::create(['id'=>'502','district_id'=>'69','name'=>'Nabi nagar']);
Thana::create(['id'=>'503','district_id'=>'69','name'=>'Kasba']);
Thana::create(['id'=>'504','district_id'=>'69','name'=>'Akhaura']);
Thana::create(['id'=>'505','district_id'=>'69','name'=>'Nachhir nagar']);
Thana::create(['id'=>'506','district_id'=>'69','name'=>'Sarail']);
Thana::create(['id'=>'507','district_id'=>'69','name'=>'Ashugonj']);
Thana::create(['id'=>'508','district_id'=>'79','name'=>'Pekua']);
Thana::create(['id'=>'509','district_id'=>'101','name'=>'Jashore Sadar']);
Thana::create(['id'=>'510','district_id'=>'101','name'=>'Baghar par']);
Thana::create(['id'=>'511','district_id'=>'101','name'=>'Avoynagar']);
Thana::create(['id'=>'512','district_id'=>'101','name'=>'Kashabpur']);
Thana::create(['id'=>'513','district_id'=>'101','name'=>'Monirampur']);
Thana::create(['id'=>'514','district_id'=>'101','name'=>'Jikorgchha']);
Thana::create(['id'=>'515','district_id'=>'101','name'=>'Chougchha']);
Thana::create(['id'=>'516','district_id'=>'101','name'=>'Sharsha']);
Thana::create(['id'=>'517','district_id'=>'97','name'=>'Chuwadanga Sudar']);
Thana::create(['id'=>'518','district_id'=>'97','name'=>'Alomdanga']);
Thana::create(['id'=>'519','district_id'=>'97','name'=>'Damurhuda']);
Thana::create(['id'=>'520','district_id'=>'97','name'=>'Jibonnagar']);
Thana::create(['id'=>'521','district_id'=>'97','name'=>'Jibonnagar']);
Thana::create(['id'=>'522','district_id'=>'98','name'=>'Jhenaiga Sudar']);
Thana::create(['id'=>'523','district_id'=>'98','name'=>'Kaliganj']);
Thana::create(['id'=>'524','district_id'=>'98','name'=>'Shylkupa']);
Thana::create(['id'=>'525','district_id'=>'98','name'=>'Kutchadpur']);
Thana::create(['id'=>'526','district_id'=>'98','name'=>'Mohashpur']);
Thana::create(['id'=>'527','district_id'=>'98','name'=>'Horinakundu']);
Thana::create(['id'=>'528','district_id'=>'98','name'=>'Horinakundu']);
Thana::create(['id'=>'529','district_id'=>'106','name'=>'Borishal Sudar']);
Thana::create(['id'=>'530','district_id'=>'106','name'=>'Bakargonj']);
Thana::create(['id'=>'531','district_id'=>'106','name'=>'Ujirpur']);
Thana::create(['id'=>'532','district_id'=>'106','name'=>'Babugonj']);
Thana::create(['id'=>'533','district_id'=>'106','name'=>'Mahandigonj']);
Thana::create(['id'=>'534','district_id'=>'106','name'=>'Hijla']);
Thana::create(['id'=>'535','district_id'=>'106','name'=>'Moladi']);
Thana::create(['id'=>'536','district_id'=>'106','name'=>'Banaripara']);
Thana::create(['id'=>'537','district_id'=>'106','name'=>'Agoiljhara']);
Thana::create(['id'=>'538','district_id'=>'106','name'=>'Gouranadi']);
Thana::create(['id'=>'540','district_id'=>'110','name'=>'Potuwakhali Sudar']);
Thana::create(['id'=>'541','district_id'=>'110','name'=>'Baufol']);
Thana::create(['id'=>'542','district_id'=>'110','name'=>'Doshmina']);
Thana::create(['id'=>'543','district_id'=>'110','name'=>'Golachipa']);
Thana::create(['id'=>'544','district_id'=>'110','name'=>'Kulapara']);
Thana::create(['id'=>'545','district_id'=>'110','name'=>'Mirzagonj']);
Thana::create(['id'=>'547','district_id'=>'110','name'=>'Dumki']);
Thana::create(['id'=>'548','district_id'=>'108','name'=>'Jhalokhati Sudar']);
Thana::create(['id'=>'549','district_id'=>'108','name'=>'Nolchhiti']);
Thana::create(['id'=>'550','district_id'=>'108','name'=>'Rajapur']);
Thana::create(['id'=>'551','district_id'=>'108','name'=>'Kathalia']);
Thana::create(['id'=>'552','district_id'=>'111','name'=>'Charfashon']);
Thana::create(['id'=>'553','district_id'=>'111','name'=>'Lalmuhon']);
Thana::create(['id'=>'554','district_id'=>'111','name'=>'Monpura']);
Thana::create(['id'=>'555','district_id'=>'111','name'=>'Tujomuddin']);
Thana::create(['id'=>'556','district_id'=>'111','name'=>'Borhanuddin']);
Thana::create(['id'=>'557','district_id'=>'111','name'=>'Bhula Sudar']);
Thana::create(['id'=>'558','district_id'=>'111','name'=>'Dhultkhan']);
Thana::create(['id'=>'559','district_id'=>'107','name'=>'Najirpur']);
Thana::create(['id'=>'560','district_id'=>'107','name'=>'Nachharabad']);
Thana::create(['id'=>'561','district_id'=>'107','name'=>'Kawkhali']);
Thana::create(['id'=>'562','district_id'=>'107','name'=>'Piroj pur Sudar']);
Thana::create(['id'=>'563','district_id'=>'107','name'=>'Vhandaria']);
Thana::create(['id'=>'564','district_id'=>'107','name'=>'Mothbaria']);
Thana::create(['id'=>'565','district_id'=>'107','name'=>'Jiyanagar']);
Thana::create(['id'=>'566','district_id'=>'109','name'=>'Amtoli']);
Thana::create(['id'=>'567','district_id'=>'109','name'=>'Betagi']);
Thana::create(['id'=>'568','district_id'=>'109','name'=>'Bamna']);
Thana::create(['id'=>'569','district_id'=>'109','name'=>'Patarghata']);
Thana::create(['id'=>'570','district_id'=>'109','name'=>'Barguna sadar']);
Thana::create(['id'=>'571','district_id'=>'65','name'=>'South surma']);
Thana::create(['id'=>'572','district_id'=>'66','name'=>'South sunamganj']);
Thana::create(['id'=>'573','district_id'=>'116','name'=>'Chand gaon']);
Thana::create(['id'=>'574','district_id'=>'116','name'=>'Chittagram bondor']);
Thana::create(['id'=>'575','district_id'=>'101','name'=>'kotyalee']);
    }
}
